services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ../../fpak
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge